### PR TITLE
Fix scrolling on touchscreens

### LINKED ISSUE #27: Slider doesn't allow scrolling up and down on touchscreen
When trying to scroll up or down on an Android phone (touchscreen) by touching anywhere on this button/card then scrolling up or down doesn't work at all. The value of the slider will usually change a bit because while trying to scroll up or down, finger usually moves slightly left or right and the slider immediately responds to this, even tho the main movement is on the up/down axis.

There's a thread about it here as well: https://github.com/mattieha/slider-button-card/issues/203

### PR DESCRIPTION
**Pull request by Pajn**
Makes the slider work on touchscreens by allowing the browser to handle the y-axis

Fixes #27

### CODE REVIEW

**Review by rohankapoorcom — CHANGES_REQUESTED** [review]
Hi @Pajn - it looks like your build.lock file is rolling back some of the upgrades that were recently released on the upstream branch. Can you revert the change to that file?

The rest of this looks great!

**Comment by Pajn** [comment]
lockfile reverted

**Review by BlackCube4 — APPROVED** [review]

**Comment by Jimmypl007** [comment]
> @rohankapoorcom Would love to see this go through!

In the meantime, they just added subviews to home assistant..

I have my lights and other slider controls in those at the moment.

**Comment by ScottG489** [comment]
Hey @Pajn! Wondering what the reason was that you closed this? Was looking forward to this change.

**Comment by Pajn** [comment]
Cleaning a lot stalled PRs to make overview of open ones in https://github.com/pulls usable. It doesn't seem I can do enything more to get thi merged. Anyone is of course super free to pick this up if they see a way forward to get it mergerd.

**Comment by ScottG489** [comment]
It's too bad no one reviewed this. I'm just considering forking the repo with this change applied.

**Comment by BlackCube4** [comment]
Damn it, this is such a simple and fundamental feature. I would love this change!

**Review by rohankapoorcom — APPROVED** [review]

**Comment by ScottG489** [comment]
Thanks so much @rohankapoorcom! When can we expect the next HACS release?

**Comment by piit79** [comment]
Awesome! Can't wait for the next release :) Thanks!

**Comment by rohankapoorcom** [comment]
It was just released in v1.10.10

**Comment by mainmind83** [comment]
This fix seems to fail on all shutter elements, so far it worked. It does not allow to select above the percentage in Android

https://user-images.githubusercontent.com/18678468/203043417-55561ab7-74e1-4261-b1cf-aeea0385e4e1.mp4

`square: false
columns: 2
type: grid
cards:
  - type: custom:slider-button-card
    entity: light.0xcc86ecfffe4e988c_l1
    slider:
      direction: left-right
      background: gradient
      use_state_color: true
    icon:
      tap_action:
        action: more-info
      use_state_color: true
      show: false
    action_button:
      mode: toggle
    name: Luz test 1
  - type: custom:slider-button-card
    entity: light.0xcc86ecfffe4e988c_l2
    slider:
      direction: left-right
      background: gradient
      use_state_color: true
      use_percentage_bg_opacity: false
      show_track: false
      toggle_on_click: false
      force_square: false
    show_name: true
    show_state: true
    compact: false
    icon:
      show: false
      use_state_color: false
      tap_action:
        action: more-info
    action_button:
      mode: toggle
      icon: mdi:power
      show: true
      show_spinner: true
      tap_action:
        action: toggle
    name: Luz test 2
  - type: custom:slider-button-card
    entity: cover.0x84b4dbfffeb5f6e9
    slider:
      direction: top-bottom
      background: striped
    icon:
      show: false
      tap_action:
        action: more-info
    action_button:
      tap_action:
        action: toggle
      mode: custom
      icon: mdi:swap-vertical
      show: false
    name: Pers. salón
    show_state: true
    compact: false
    invert: true
  - type: custom:slider-button-card
    entity: cover.0x842e14fffe15c240
    slider:
      direction: top-bottom
      background: striped
    icon:
      show: false
      tap_action:
        action: more-info
    action_button:
      tap_action:
        action: toggle
      mode: custom
      icon: mdi:swap-vertical
      show: false
    name: Pers. test A
    invert: true
  - type: custom:slider-button-card
    entity: cover.0x84b4dbfffeb8ad4d
    slider:
      direction: top-bottom
      background: striped
    icon:
      show: false
      tap_action:
        action: more-info
    action_button:
      tap_action:
        action: toggle
      mode: custom
      icon: mdi:swap-vertical
      show: false
    name: Pers. test B
    invert: true
title: Salón`

**Comment by Tammarko** [comment]
> This fix seems to fail on all shutter elements, so far it worked. It does not allow to select above the percentage in Android
> 
Confirming same behaviour, the shutters are now difficult to control.

**Comment by rohankapoorcom** [comment]
Hey @Pajn - do you mind taking a look at this bug report with the cover elements?

**Pull request merged**
